"""Bake reusable RGB565+alpha lighting masks; no runtime blur or extra fonts."""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1]


def distance(x, y, w, h, radius, inset=0):
    qx = abs(x - w / 2) - (w / 2 - inset - radius)
    qy = abs(y - h / 2) - (h / 2 - inset - radius)
    return math.hypot(max(qx, 0), max(qy, 0)) + min(max(qx, qy), 0) - radius


def pixels(w, h, mode):
    data = []
    for y in range(h):
        for x in range(w):
            if mode == 'shadow':
                d = distance(x + .5, y + .5, w, h, 18, 5)
                dark = math.exp(-max(distance(x - 2, y - 3, w, h, 18, 5), 0) / 3) * .72
                light = math.exp(-max(distance(x + 2, y + 3, w, h, 18, 5), 0) / 2) * .18
                value = light - dark
                coverage = min(1, max(0, d + 1))
            else:
                d = distance(x + .5, y + .5, w, h, 16)
                coverage = min(1, max(0, .5 - d))
                # Blend four soft edge lights without diagonal normal seams.
                if mode == 'raised':
                    value = (.19 * math.exp(-y / 5) + .09 * math.exp(-x / 5)
                             - .36 * math.exp(-(h - 1 - y) / 6)
                             - .22 * math.exp(-(w - 1 - x) / 6)
                             + .025 - .06 * y / h)
                else:
                    value = (-.64 * math.exp(-y / 10) - .32 * math.exp(-x / 9)
                             + .10 * math.exp(-(h - 1 - y) / 5)
                             + .04 * math.exp(-(w - 1 - x) / 5) - .04)
            # Stable tiny dither softens RGB565 banding on the physical LCD.
            noise = (((x * 73 + y * 179 + x * y * 13) % 17) - 8) * .8
            alpha = int(max(0, min(230, abs(value) * 255 + noise)) * coverage)
            data.extend((255 if value > 0 else 0, 255 if value > 0 else 0, alpha))
    return data


parts = ['/* Generated by tools/generate_neumorphic.py. */', '#include "sc_pad_neumorphic.h"',
         '#if LV_COLOR_DEPTH != 16 || LV_COLOR_16_SWAP != 0',
         '#error "Neumorphic assets require native RGB565"', '#endif']
button_sizes = [(233, 132), (137, 100), (137, 120), (449, 56),
                (213, 222), (137, 222), (449, 190), (449, 38)]
assets = []
for outer_w, outer_h in button_sizes:
    assets.append(('shadow', outer_w, outer_h))
    assets.append(('raised', outer_w - 8, outer_h - 8))
    assets.append(('inset', outer_w - 8, outer_h - 8))

for mode, w, h in assets:
    name = f'{mode}_{w}x{h}'
    data = pixels(w, h, mode)
    parts.append(f'static const uint8_t {name}_pixels[] = {{')
    parts.extend('    ' + ','.join(str(v) for v in data[i:i+30]) + ',' for i in range(0, len(data), 30))
    parts.append('};')
    parts.append(f'static const lv_img_dsc_t sc_pad_neu_{name} = {{\n'
                 f'    .header = {{.cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .reserved = 0, .w = {w}, .h = {h}}},\n'
                 f'    .data_size = sizeof({name}_pixels), .data = {name}_pixels\n}};')

parts.append('const lv_img_dsc_t *sc_pad_neu_image(int width, int height, sc_pad_neu_kind_t kind) {')
for outer_w, outer_h in button_sizes:
    inner_w, inner_h = outer_w - 8, outer_h - 8
    parts.append(f'    if (width == {outer_w} && height == {outer_h} && kind == SC_PAD_NEU_SHADOW) return &sc_pad_neu_shadow_{outer_w}x{outer_h};')
    parts.append(f'    if (width == {inner_w} && height == {inner_h} && kind == SC_PAD_NEU_RAISED) return &sc_pad_neu_raised_{inner_w}x{inner_h};')
    parts.append(f'    if (width == {inner_w} && height == {inner_h} && kind == SC_PAD_NEU_INSET) return &sc_pad_neu_inset_{inner_w}x{inner_h};')
parts.append('    return 0;\n}')
(ROOT / 'src/sc_pad_neumorphic.c').write_text('\n'.join(parts) + '\n')
